### ISSUE TITLE
`pod install` problem - target has transitive dependencies that include static binaries: (/Users/BLAH/BLAH/Pods/Taplytics/Taplytics.framework)

### ISSUE THREAD

**Issue by richardPFisk** [segment-integrations/analytics-ios-integration-taplytics#10]
I'm having problems installing `pod 'Segment-Taplytics'`. Upon executing `pod install` with the version of Cocoapods 1.1 or 1.2, I get the following error ` target has transitive dependencies that include static binaries: (/Users/BLAH/BLAH/Pods/Taplytics/Taplytics.framework)`.

Things I have tried: 
* modifying the Segment-Taplytics podspec in a forked repo with `s.vendored_libraries = 'Taplytics.framework'`
* modifying the Segment-Taplytics podspec in a forked repo with no `s.dependency 'Taplytics', '~> 2.13.0'` and manually including the `pod 'Taplytics'`

I was wondering whether anyone else had experienced or solved this problem/type of problem before.

Thanks in advance.

**Comment by richardPFisk** [comment]
It is also repeatable using a bare-bones project created from scratch.

* CocoaPods version 1.2
* Xcode version 8.2.1

Error:
```Installing Analytics (3.6.0)
Installing Segment-Taplytics (1.1.0)
Installing Taplytics (2.13.1)
[!] The 'Pods-integrationTest' target has transitive dependencies that include static binaries: (/Users/rfisk/Projects/integrationTest/Pods/Taplytics/Taplytics.framework)
```

Podfile:
```
use_frameworks!
platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target :integrationTest do
    pod 'Segment-Taplytics'
end
```

**Comment by ladanazita** [comment]
Hi @richardPFisk !

We have seen this before with integrations that do not serve dynamic frameworks. 

You can follow the thread [here](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3), and we have had a work around for some integrations such as [Google Analytics](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/14/files). You will need to copy the integration code manually into your project, then depend on Taplytics directly. Here is an [example](https://github.com/segmentio/TestAppSwiftUseFrameworksStaticLib) of a Swift app using the GA work around.

**Comment by richardPFisk** [comment]
Thanks @ladanazita! This will definitely work. And, I used this method for another integration. It is shame to have to do this though.

Further investigation that `pod spec lint` also fails with the same error:
```
git clone https://github.com/segment-integrations/analytics-ios-integration-taplytics.git
cd analytics-ios-integration-taplytics
pod spec lint
```
Error:
```
 -> Segment-Taplytics (1.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/7d/gts84ltx2yd8lp5p_5drybz8xnzb50/T/CocoaPods/Lint/Pods/Taplytics/Taplytics.framework)) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

**Comment by ladanazita** [comment]
Yeah definitely unfortunate. 😞 

Can you try using `lint` with `--use-libraries`?

**Comment by richardPFisk** [comment]
I can confirm that `pod spec lint  --use-libraries` works correctly.

Also, patching the CocoaPods ruby `def verify_no_static_framework_transitive_dependencies` to just `return`, results in the error experienced in the integrated workspace/project:
```
 pod spec lint

 -> Segment-Taplytics (1.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  Segment-Taplytics/Segment-Taplytics/Classes/SEGTaplyticsIntegration.h:11:9: fatal error: 'Taplytics/Taplytics.h' file not found

Analyzed 1 podspec.
```
